### ISSUE TITLE
"All Mimic3 public servers are down, please self host mimic3" depending the utterance

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-tts-plugin-mimic3-server#9]
If my utterance got an accent `é` like `quand es-tu né`, the plugin says `All Mimic3 public servers are down, please self host mimic3` which is not true.

```
2023-05-14 13:55:52.846 - audio - ovos_audio.service:execute_tts:316 - ERROR - TTS synth failed! All Mimic3 public servers are down, please self host mimic3
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/service.py", line 314, in execute_tts
    self.tts.execute(utterance, ident, listen)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 716, in execute
    self._execute(sentence, ident, listen, **kwargs)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 742, in _execute
    audio_file, phonemes = self.synth(sentence, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 812, in synth
    audio.path, phonemes = self.get_tts(sentence, str(audio), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_tts_plugin_mimic3_server/__init__.py", line 120, in get_tts
    audio_data = self._get_from_public_servers(voice, sentence)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_tts_plugin_mimic3_server/__init__.py", line 143, in _get_from_public_servers
    raise RemoteTTSException(f"All Mimic3 public servers are down, please self host mimic3")
```

**Comment by goldyfruit** [comment]
If i'm using directly the URL of one of them (e.g https://tts.smartgic.io/mimic3/api/tts) via the `url` option, I don't get any issue.

**Comment by goldyfruit** [comment]
`Who may do?` utterance, returns the same behaviour, I think the plugin doesn't like some chars.

```
2023-06-03 12:48:32.576 - audio - ovos_audio.service:execute_tts:319 - INFO - Speak: To Whom It May Concern: Ka Shen's Journey (Chinese: 家倩的人生之旅; pinyin: Jiā Qiàn de Rén Shēng Zhī Lǚ) is a 2009 docudrama about actress Nancy Kwan.
2023-06-03 12:48:32.860 - audio - ovos_tts_plugin_mimic3_server:_validate_args_combo:93 - WARNING - lang defined twice! choosing en_GB over en_US for voice: en_UK/apope_low
2023-06-03 12:48:34.240 - audio - ovos_audio.service:execute_tts:324 - ERROR - TTS synth failed! All Mimic3 public servers are down, please self host mimic3
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_audio/service.py", line 322, in execute_tts
    self.tts.execute(utterance, ident, listen)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 716, in execute
    self._execute(sentence, ident, listen, **kwargs)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 742, in _execute
    audio_file, phonemes = self.synth(sentence, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 812, in synth
    audio.path, phonemes = self.get_tts(sentence, str(audio), **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_tts_plugin_mimic3_server/__init__.py", line 120, in get_tts
    audio_data = self._get_from_public_servers(voice, sentence)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_tts_plugin_mimic3_server/__init__.py", line 143, in _get_from_public_servers
    raise RemoteTTSException(f"All Mimic3 public servers are down, please self host mimic3")
ovos_plugin_manager.templates.tts.RemoteTTSException: All Mimic3 public servers are down, please self host mimic3
2023-06-03 12:48:34.257 - audio - ovos_audio.service:execute_fallback_tts:351 - DEBUG - TTS fallback, utterance : To Whom It May Concern: Ka Shen's Journey (Chinese: 家倩的人生之旅; pinyin: Jiā Qiàn de Rén Shēng Zhī Lǚ) is a 2009 docudrama about actress Nancy Kwan.
2023-06-03 12:48:34.396 - audio - ovos_plugin_manager.templates.tts:_execute:761 - DEBUG - no mouth movements available! unknown visemes for To Whom It May Concern: Ka Shen's Journey (Chinese: 家倩的人生之旅; pinyin: Jiā Qiàn de Rén Shēng Zhī Lǚ) is a 2009 docudrama about actress Nancy Kwan.
```

**Comment by goldyfruit** [comment]
When forcing my server into the `tts` section, I don't get the error.

```json
  "tts": {
    "module": "ovos-tts-plugin-mimic3-server",
    "ovos-tts-plugin-mimic3-server": {
      "voice": "en_UK/apope_low",
      "url": "http://192.168.1.140:59125/api/tts"
    }
}
```

**Comment by ChanceNCounter** [comment]
Finding: this error is raised no matter what goes wrong with the request. If the request doesn't come back OK, we get "all public servers are down"
